name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  gh-release:
    name: GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: |
          make \
            -j $(($(nproc)+1)) \
            --no-builtin-rules \
            --no-builtin-variables \
            --warn-undefined-variables
      - name: Create Release Draft
        uses: softprops/action-gh-release@v1
        with:
          files: build/bin/*
          draft: true
  docker:
    name: Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Log in Docker Hub
        uses: docker/login-action@v2
        with:
          username: hgl0
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Log in GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: hgl
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: |
            hgl0/nginxh
            ghcr.io/hgl/nginxh
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - uses: docker/build-push-action@v4
        with:
          push: true
          file: nginx/docker/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
