name: Release

on:
  push:
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    name: Release Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v2
        with:
          username: hgl0
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: |
            hgl0/nginxh
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - uses: docker/build-push-action@v4
        with:
          push: true
          file: nginx/docker/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
